wandb_version: 1

task_name:
  desc: null
  value: short_term_forecast
is_training:
  desc: null
  value: 1
model_id:
  desc: null
  value: m4_layer_2_Quarterly
model:
  desc: null
  value: CARD
data:
  desc: null
  value: m4
root_path:
  desc: null
  value: ./dataset/m4
data_path:
  desc: null
  value: ETTh1.csv
features:
  desc: null
  value: M
target:
  desc: null
  value: OT
freq:
  desc: null
  value: h
checkpoints:
  desc: null
  value: ./checkpoints/
seq_len:
  desc: null
  value: 96
label_len:
  desc: null
  value: 48
pred_len:
  desc: null
  value: 96
seasonal_patterns:
  desc: null
  value: Quarterly
mask_rate:
  desc: null
  value: 0.25
anomaly_ratio:
  desc: null
  value: 0.25
top_k:
  desc: null
  value: 5
num_kernels:
  desc: null
  value: 6
enc_in:
  desc: null
  value: 1
dec_in:
  desc: null
  value: 1
c_out:
  desc: null
  value: 1
d_model:
  desc: null
  value: 128
n_heads:
  desc: null
  value: 16
e_layers:
  desc: null
  value: 2
d_layers:
  desc: null
  value: 1
d_ff:
  desc: null
  value: 256
moving_avg:
  desc: null
  value: 25
factor:
  desc: null
  value: 3
distil:
  desc: null
  value: true
dropout:
  desc: null
  value: 0.1
embed:
  desc: null
  value: timeF
activation:
  desc: null
  value: gelu
output_attention:
  desc: null
  value: false
num_workers:
  desc: null
  value: 10
itr:
  desc: null
  value: 1
train_epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 128
patience:
  desc: null
  value: 400
learning_rate:
  desc: null
  value: 0.0005
des:
  desc: null
  value: Exp
loss:
  desc: null
  value: SMAPE
lradj:
  desc: null
  value: CARD
use_amp:
  desc: null
  value: false
use_gpu:
  desc: null
  value: true
gpu:
  desc: null
  value: 0
use_multi_gpu:
  desc: null
  value: false
devices:
  desc: null
  value: 0,1,2,3
p_hidden_dims:
  desc: null
  value:
  - 128
  - 128
p_hidden_layers:
  desc: null
  value: 2
alpha:
  desc: null
  value: 0.5
beta:
  desc: null
  value: 0.5
dp_rank:
  desc: null
  value: 8
rescale:
  desc: null
  value: 1
fc_dropout:
  desc: null
  value: 0.3
head_dropout:
  desc: null
  value: 0.3
patch_len:
  desc: null
  value: 4
stride:
  desc: null
  value: 1
momentum:
  desc: null
  value: 0.1
optimizer:
  desc: null
  value: adam
local_rank:
  desc: null
  value: 0
devices_number:
  desc: null
  value: 1
use_statistic:
  desc: null
  value: false
use_decomp:
  desc: null
  value: false
same_smoothing:
  desc: null
  value: false
warmup_epochs:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0
merge_size:
  desc: null
  value: 2
use_untoken:
  desc: null
  value: 0
pct_start:
  desc: null
  value: 0.3
seg_len:
  desc: null
  value: 6
win_size:
  desc: null
  value: 2
fix_seed:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    code_path: code/short_term_forecast_m4/run.py
    python_version: 3.9.18
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695940424.793498
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
